apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: ram-ns
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - nodePort: 32643
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
