apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: 89912-dev
spec:
  limits:
  - default:
      memory: 50Mi
      cpu: 0.1
    defaultRequest:  
      memory: 50Mi
      cpu: 0.1
    type: Container
