apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-quota
  namespace: 89912-dev
  labels:
    app: quota-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota-test
  template:
    metadata:
      labels:
        app: quota-test
    spec:
      containers:
      - image: busybox
        name: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 300" ]
