# This quota will set the below restrictions for namespace = 89912-dev
# Max No.of Pods can be spin-up = 2
# Max no.of configmap can be created = 1


apiVersion: v1
kind: ResourceQuota
metadata:
  name: 89912-dev-quota
  namespace: 89912-dev
spec:
  hard:
    pods: "2"
    configmaps: "1"
    limits.memory: "100Mi"
    limits.cpu: "10k"
