apiVersion: v1
kind: Pod
metadata:
  name: pod-pv-demo
  labels:
    run: nginx

spec:
  volumes:
    - name: home-path
      persistentVolumeClaim:
        claimName: pvc-hostpath

  containers:
    - name: nginx
      image: docker.io/nginx:latest
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-path
      ports:
        - containerPort: 80

