apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
spec:
  storageClassName: nfs-dynamic-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
