apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
  
spec:
  volumes:
    - name: hostpath-san
      persistentVolumeClaim:
        claimName: local-pvc

  containers:
    - name: nginx
      image: docker.io/nginx:latest
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: hostpath-san
      ports:
        - containerPort: 80
   
  initContainers:    
    - name: init-container
      image: docker.io/busybox:latest
      volumeMounts:
        - mountPath: "/mnt"
          name: hostpath-san
      command: ["/bin/sh"]
      args: ["-c", "touch /mnt/index.html" ]
