apiVersion: v1
kind: Pod
metadata: 
  name: mongodb
  labels:
    app: mongodb
    role: database
spec:
  containers:
  - name: mongodb-container
    image: docker-registry.lab.net:5000/mongo:latest
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: password
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongo-data-volume-nfs
