apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
    role: database
    tier: backend
spec:
  ports:
    - port: 27017
  type: ClusterIP
  selector:
    app: mongodb
    role: database
    tier: backend
