apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vol-1
  labels:
    type: local
spec:
  storageClassName: NFSMOUNT
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: kube-master.lab.net
    path: /storage/persistent-volumes
