apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green-deploy
  labels:
    app: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: docker-registry.lab.net:5000/busybox 
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1> <font color=green> NGNIX Web Service running in GREEN </font></h1>" > /webdata/index.html']
      containers:
      - image: docker-registry.lab.net:5000/nginx:latest
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
