apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod

spec:
  volumes:
  - name: mysql-env
    configMap:
      name: mysql-env
      items:
        - key: mysql.cnf
          path: my.cnf
  containers:
  - image: busybox
    name: busybox
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 300" ]
    volumeMounts:
    - name: mysql-env
      mountPath: /mysql-config
  
