apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 300" ]
    env:
    - name: FIRSTNAME  # Varibale inside container
      valueFrom:
        configMapKeyRef:
          name: ram-cm
          key: first.name
    - name: LASTNAME  # variable inside container
      valueFrom:
        configMapKeyRef:
          name: ram-cm
          key: last.name
