apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  volumes:
  - name: env-var
    configMap:
      name: ram-cm
  containers:
  - image: busybox
    name: busybox
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 300" ]
    volumeMounts:
    - name: env-var
      mountPath: /secrets
