apiVersion: v1
kind: Pod
metadata:
  name: secret-vol

spec:
  volumes:
  - name: secret-volume
    secret:      
      secretName: ram-cred
  
  containers:
  - image: busybox
    name: busybox
    command: [ "/bin/sh"]
    args: ["-c", "sleep 300"]
    volumeMounts:
    - name: secret-volume
      mountPath: /secure   
