apiVersion: v1
kind: Pod
metadata:
  name: secret-env

spec:
  containers:
  - image: busybox
    name: busybox
    command: [ "/bin/sh"]
    args: ["-c", "sleep 300"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: ram-cred
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: ram-cred
          key: password
    - name: COMMENT
      valueFrom:
        secretKeyRef:
          name: ram-cred
          key: comment
     
